// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_palabra from "./routes/api/palabra.tsx";
import * as $index from "./routes/index.tsx";
import * as $wordcsr from "./routes/wordcsr.tsx";
import * as $wordssr from "./routes/wordssr.tsx";
import * as $Clientside from "./islands/Clientside.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/palabra.tsx": $api_palabra,
    "./routes/index.tsx": $index,
    "./routes/wordcsr.tsx": $wordcsr,
    "./routes/wordssr.tsx": $wordssr,
  },
  islands: {
    "./islands/Clientside.tsx": $Clientside,
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
